Remove `net.peer.port`,`net.peer.ip` and `net.peer.name` from server metrics
bufbuild/connect-opentelemetry-go pull request #37
Opened 2022-12-15 15:44 UTC by joshcarp

Only add `parseAddress` attributes if the `isClient` flag is true. 

If it is a `Cllient` interceptor then these will have relatively low cardinality: `net.peer.port` would be the port the server is listening on (8080 or 443 for example). `net.peer.ip` would be the ip address of the server (again, low cardinality). `net.peer.name` would also be the server name (api.buf.build).

2022-12-15 16:12 UTC, pkwarren approved these changes

2022-12-15 16:15 UTC, akshayjshah reviewed
Think we should remove these from the client as well. Port and IP are often very high-cardinality over time, since backend services move around clusters on every deployment. Name is potentially ok, but it's not worth keeping by itself.

We can re-introduce them later as an opt-in.

2022-12-15 16:16 UTC, joshcarp commented
That simplifies it a lot

2022-12-15 17:03 UTC, doriable approved these changes

2022-12-15 17:03 UTC, doriable commented
This can be a follow-up PR, but we should note this in our README.

2022-12-15 17:55 UTC, lrewega commented
`net.peer.ip` seems reasonable to drop, I can't find that in the spec anywhere either.

`net.peer.port` is conditionally required (when not `80` or `443`) so I suspect it's fine to include conditionally. It's effectively a constant.

`net.peer.name` seems like it should be stable, given it's usually a hostname and perhaps rarely a hard-coded IP address. Effectively a constant.

The spec makes some reasonable recommendations IMO: https://opentelemetry.io/docs/reference/specification/metrics/semantic_conventions/rpc-metrics/#attributes

I think perhaps there is some confusion around _local_ IPs and ports, which don't seem like they would be relevant in most scenarios.

2022-12-15 18:05 UTC, joshcarp commented
Yeah so I've been chatting with @doriable and I am going to:
- Remove the server attributes for `net.peer.port` `net.peer.ip` and `net.peer.name` 
- Keep them in for Clients
This way it's lower cardinality but it still conforms to the spec 👍

2022-12-15 18:07 UTC, lrewega commented
I don't see any reason why `net.peer.port` and `net.peer.name` would have higher cardinality on the server -- they're effectively constant for the lifetime of the server, and likely constant across instances as well. If anything the client cardinality seems like it would be higher if a client interacted with many remotes.

2022-12-15 18:14 UTC, lrewega commented
I missed the part about `net.peer.port` being optional for the server, as "it describes the port the client is connecting from" -- reasonable to omit from the server indeed.

2022-12-15 18:35 UTC, akshayjshah requested changes
I'll look into the exact proposed change in detail tonight and gather a more formed thought.

My impression is that some of this discussion is about whether the OTel spec is reasonable. The rest of the discussion is about whether what we're actually doing is reasonable. There's also the broader point that nobody gets anything concrete by adhering to the OTel "specification" - I've yet to run into _any_ observability platform that uses these specifications to automatically configure dashboards, alerts, or anything else.

I'd like some time this evening to fully understand the problems we're running into internally and the impact of these proposed changes.

2022-12-19 18:30 UTC, akshayjshah commented
OK, here's my understanding of the situation.

## OpenTelemetry Specification

First, the OpenTelemetry specification asks for the following (from the [RPC metrics semantic conventions](https://opentelemetry.io/docs/reference/specification/metrics/semantic_conventions/rpc-metrics/#attributes) and the [RPC span semantic conventions](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/rpc/)):

* `net.peer.name`: RPC server host name (e.g., `example.com`). May contain server IP address, DNS name, or local socket name. If the host is an IP address, instrumentations should not do a reverse proxy lookup to obtain DNS name and should set `net.peer.name` to the IP address provided in the host component. Required.
* `net.peer.port`: Logical remote port number (e.g., 80, 8080, 443). Required if different than `net.peer.name` and if `net.sock.peer.addr` is set.
* `net.sock.peer.addr`: Remote socket peer address: IPv4 or IPv6 for internet protocols, path for local communication, etc.
* `net.peer.ip`: doesn't appear at all. (I think I may have pulled this from the OpenTracing specification somehow?)
* At least one of `net.peer.name` and `net.sock.peer.addr` is required.
  * To avoid high cardinality, implementations should prefer the most stable of `net.peer.name` or `net.sock.peer.addr`, depending on expected deployment profile. For many cloud applications, this is likely `net.peer.name` as names can be recycled even across re-instantiation of a server with a different ip.
  * For client-side metrics `net.peer.port` is required if the connection is IP-based and the port is available (it describes the server port they are connecting to). For server-side spans `net.peer.port` is optional (it describes the port the client is connecting from). Furthermore, setting [`net.transport`](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/span-general/#network-transport-attributes) is required for non-IP connection like named pipe bindings.

## `connect.Peer`

Second, here's the information we actually have available from `net/http`, laundered through `connect.Peer`:

* Handler: peer address in IP:port format.
* Client: host and port portion of server URL, in host:port or IP:port format (depending on the `baseURL` the client used to configure the HTTP client).

## Plan: Handlers

We should set `net.peer.name` and `net.peer.port` to the remote IP address and port.

This follows the specification, but seems likely to be _very_ high cardinality. It would be somewhat better if we knew the client's hostname instead of using an IP, but I can't imagine how any server would get that information without a reverse DNS lookup. Maybe we could get it from the client certificate in an mTLS handshake? Internally, I expect that we'll want to drop these tags.

Since many users will probably also want to drop this information, we should expose an option to not emit these tags at all.

## Plan: Clients

We should set `net.peer.name` and `net.peer.port` to the remote host/IP and port. In many use cases, this should be _relatively_ low-cardinality, because I expect that most users will be using URLs like `https://demo.connect.build:443/some.Service/Method`.

Anyone using URLs with explicit IPs, or ports that change relatively often, is in for a lot of pain. For symmetry with handlers, I think it's probably fine to expose an option to suppress these tags.

## What next?

If everyone agrees, I'll open a PR to implement this plan and update the docs. I'd like a thumbs-up from @joshcarp, @doriable, and @lrewega at least, though anyone else is welcome to chime in.

2022-12-28 09:47 UTC, lujiajing1126 commented
Wait for this PR. High cardinality is continously causing OOM

2023-01-05 16:02 UTC, joshcarp commented
Closing because https://github.com/bufbuild/connect-opentelemetry-go/pull/41 allows the same thing to be acomplished

2023-01-05 16:02 UTC, closed without merging